services:
  postgres:
    image: postgres:16
    container_name: mds-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: etl_target
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d etl_target"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  postgres_data:
