CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS harmonized;
CREATE SCHEMA IF NOT EXISTS serving;
CREATE TABLE IF NOT EXISTS raw.pipeline_metadata (pipeline_name TEXT PRIMARY KEY, last_run_at TIMESTAMPTZ);
